"""empty message

Revision ID: 9024a6d758d1
Revises: 9c33b5bbef29
Create Date: 2024-09-03 23:17:32.051294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9024a6d758d1'
down_revision: Union[str, None] = '9c33b5bbef29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###
