"""empty message

Revision ID: 9c33b5bbef29
Revises: a7bca08a8127
Create Date: 2024-08-12 14:52:39.955838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c33b5bbef29'
down_revision: Union[str, None] = 'a7bca08a8127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('address', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('reviews', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'longitude')
    op.drop_column('reviews', 'latitude')
    op.drop_column('reviews', 'address')
    # ### end Alembic commands ###
